- src/main/webapp/WEB-INF/views/admin/adoptreg_insert.jsp
- src/main/webapp/WEB-INF/views/admin/adoptreg_list.jsp
- src/main/webapp/WEB-INF/views/admin/adoptreg_update.jsp
- src/main/webapp/WEB-INF/views/admin/board_insert.jsp
- src/main/webapp/WEB-INF/views/admin/board_list.jsp
- src/main/webapp/WEB-INF/views/admin/board_update.jsp
- src/main/webapp/WEB-INF/views/admin/cat_content.jsp
- src/main/webapp/WEB-INF/views/admin/cat_list.jsp
- src/main/webapp/WEB-INF/views/admin/dog_content.jsp
- src/main/webapp/WEB-INF/views/admin/dog_list.jsp
- src/main/webapp/WEB-INF/views/admin/notice_content.jsp
- src/main/webapp/WEB-INF/views/admin/notice_insert.jsp
- src/main/webapp/WEB-INF/views/admin/notice_list.jsp
- src/main/webapp/WEB-INF/views/admin/notice_update.jsp
- src/main/webapp/WEB-INF/views/admin/pet_insert.jsp
- src/main/webapp/WEB-INF/views/admin/pet_update.jsp
- src/main/webapp/WEB-INF/views/admin/review_list.jsp
- src/main/webapp/WEB-INF/views/admin/review_update.jsp
- src/main/webapp/WEB-INF/views/admin/support_insert.jsp
- src/main/webapp/WEB-INF/views/admin/support_list.jsp
- src/main/webapp/WEB-INF/views/admin/support_update.jsp
- src/main/webapp/WEB-INF/views/admin/user_content.jsp
- src/main/webapp/WEB-INF/views/admin/user_insert.jsp
- src/main/webapp/WEB-INF/views/admin/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user_update.jsp
- target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
> admin css 경로 update

- src/main/java/com/heartpet/action/QnaDAOImpl.java
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
> admin header

- .settings/org.eclipse.core.resources.prefs
- src/main/java/com/heartpet/action/CatDAO.java
- src/main/java/com/heartpet/action/DogDAO.java
- src/main/java/com/heartpet/action/DogDAOImpl.java
- src/main/java/com/heartpet/action/NoticeDAOImpl.java
- src/main/java/com/heartpet/action/QnaDAO.java
- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/model/DogDTO.java
- src/main/java/com/heartpet/model/NoticeDTO.java
- src/main/java/com/heartpet/model/QnaDTO.java
- src/main/java/com/heartpet/project/HomeController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/home.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- target/classes/mybatis-config.xml
> dao,controller 수정

- src/main/webapp/WEB-INF/views/admin/adoptreg_insert.jsp
- src/main/webapp/WEB-INF/views/admin/adoptreg_list.jsp
- src/main/webapp/WEB-INF/views/admin/adoptreg_update.jsp
- src/main/webapp/WEB-INF/views/admin/board_insert.jsp
- src/main/webapp/WEB-INF/views/admin/board_list.jsp
- src/main/webapp/WEB-INF/views/admin/board_update.jsp
- src/main/webapp/WEB-INF/views/admin/cat_content.jsp
- src/main/webapp/WEB-INF/views/admin/cat_list.jsp
- src/main/webapp/WEB-INF/views/admin/dog_content.jsp
- src/main/webapp/WEB-INF/views/admin/dog_list.jsp
- src/main/webapp/WEB-INF/views/admin/notice_content.jsp
- target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
> admin 일부 경로 수정

- src/main/java/com/heartpet/action/NoticeDAOImpl.java
- src/main/java/com/heartpet/model/NoticeDTO.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/notice.xml
- target/classes/mapper/notice.xml
> notice finish

- src/main/java/com/heartpet/action/QnaDAOImpl.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/qna.xml
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/qna/fnq_list.jsp
- src/main/webapp/WEB-INF/views/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/qna/qna_insert.jsp
- src/main/webapp/WEB-INF/views/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/qna/qna_update.jsp
- src/main/webapp/WEB-INF/views/review/review_content.jsp
- src/main/webapp/WEB-INF/views/review/review_insert.jsp
- src/main/webapp/WEB-INF/views/review/review_list.jsp
- src/main/webapp/WEB-INF/views/review/review_update.jsp
- target/classes/mapper/qna.xml
> short icon 오류 해결

- src/main/java/com/heartpet/action/MypageDAO.java
- src/main/java/com/heartpet/action/MypageDAOImpl.java
- src/main/java/com/heartpet/model/Mypage_SupportDTO.java
- src/main/resources/mapper/mypage.xml
- target/classes/mapper/mypage.xml
- target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
> xml create

- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_grade_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_content.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_list.jsp
> include path update

- src/main/webapp/WEB-INF/views/user/support/support.jsp
> support update

- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/mypage.xml
- target/classes/mapper/mypage.xml
> usercontroller

- src/main/java/com/heartpet/project/UserController.java
> usercontroller finish

- src/main/java/com/heartpet/project/QnaController.java
- src/main/java/com/heartpet/project/ReviewController.java
- src/main/webapp/WEB-INF/views/user/qna/fnq_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_insert.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_update.jsp
- src/main/webapp/WEB-INF/views/user/review/review_insert.jsp
- src/main/webapp/WEB-INF/views/user/review/review_list.jsp
- src/main/webapp/WEB-INF/views/user/review/review_update.jsp
> Controller 분리

- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/user.xml
- target/classes/mapper/user.xml
- target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
> user.xml update

- src/main/java/com/heartpet/action/MypageDAO.java
- src/main/java/com/heartpet/action/MypageDAOImpl.java
- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_grade_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- target/classes/mapper/mypage.xml
> 2202 12 07 finish

- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/WEB-INF/views/include/user_footer.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/resources/css/admin_include.css
- src/main/webapp/resources/js/signin_up.js
> footer 관리자 링크 수정

- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/webapp/WEB-INF/views/admin/user/user_content.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_insert.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
> 관리자 페이지 수정

- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/resources/mapper/qna.xml
- target/classes/mapper/qna.xml
> qna_delete 거의 완성

- src/main/java/com/heartpet/action/MypageDAO.java
- src/main/java/com/heartpet/action/MypageDAOImpl.java
- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- target/classes/mapper/mypage.xml
> user_profile update

- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_insert.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/resources/css/admin_include.css
- src/main/webapp/resources/css/admin_update.css
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/user.xml
> 관리자 user page 수정중

- src/main/java/com/heartpet/model/QnaDTO.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/webapp/WEB-INF/views/user/qna/qna_insert.jsp
> 글 작성 시 로그인 여부 체크

- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- target/classes/mapper/mypage.xml
> dog, animal

- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- target/classes/mapper/user.xml
> user dog, animal

- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
> dog animal

- src/main/java/com/heartpet/action/ReviewDAO.java
- src/main/java/com/heartpet/action/ReviewDAOImpl.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_list.jsp
- src/main/webapp/resources/css/user_review.css
- src/main/webapp/resources/js/user_review_list.js
- target/classes/mapper/review.xml
> 강아지/고양이 버튼 선택 가능

- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/webapp/WEB-INF/views/user/qna/fnq_insert.jsp
> fnq_insert 만드는 중

- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
> list update

- src/main/java/com/heartpet/action/QnaDAO.java
- src/main/java/com/heartpet/action/QnaDAOImpl.java
- src/main/java/com/heartpet/model/FnqDTO.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/resources/mapper/qna.xml
- src/main/webapp/WEB-INF/views/user/qna/fnq_update.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_insert.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_update.jsp
- src/main/webapp/WEB-INF/views/user/review/review_insert.jsp
- src/main/webapp/WEB-INF/views/user/review/review_update.jsp
- target/classes/mapper/qna.xml
> Fnq CRUD 중

- src/main/webapp/WEB-INF/views/admin/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/resources/css/list_view.css
> delete modal 추가

- src/main/java/com/heartpet/project/AdminController.java
- src/main/webapp/WEB-INF/views/admin/user/user_content.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/user/callback.jsp
- src/main/webapp/resources/css/admin_include.css
- src/main/webapp/resources/css/list_view.css
- src/main/webapp/resources/css/user_include.css
- src/main/webapp/resources/js/signin_up.js
> admin user 수정중

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/user.xml
> admin user 수정중2

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_content.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/user.xml
> 관리자 update 수정중

- src/main/java/com/heartpet/action/BoardDAO.java
- src/main/java/com/heartpet/action/QnaDAO.java
- src/main/java/com/heartpet/action/QnaDAOImpl.java
- src/main/java/com/heartpet/admin/AdminQnaController.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_reply_insert.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- src/main/webapp/resources/css/list_view.css
- src/main/webapp/resources/css/user_include.css
- src/main/webapp/resources/css/user_qna.css
> qna_reply_insert 수정 및 소소한 수정

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- src/main/webapp/resources/css/admin_update.css
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/user.xml
> 관리자 user update,delete 수정

- src/main/java/com/heartpet/action/SupportDAO.java
- src/main/java/com/heartpet/action/SupportDAOImpl.java
- src/main/java/com/heartpet/admin/AdminSupportController.java
- src/main/java/com/heartpet/model/NoticeDTO.java
- src/main/java/com/heartpet/model/SupportDTO.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/resources/mapper/support.xml
- src/main/webapp/WEB-INF/views/admin/support_insert.jsp
- src/main/webapp/WEB-INF/views/admin/support_list.jsp
- src/main/webapp/WEB-INF/views/admin/support_update.jsp
- src/main/webapp/WEB-INF/views/user/support/support_insert.jsp
- target/classes/mapper/support.xml
> admin support

- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/resources/mapper/qna.xml
- src/main/webapp/WEB-INF/views/user/qna/fnq_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- target/classes/mapper/qna.xml
> user qna 진입 오류 수정

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/admin_main.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- target/classes/mapper/user.xml
> 관리자 user list 페이징

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/UserController.java
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/resources/css/user_include.css
- src/main/webapp/resources/js/signin_up.js
> header & list

- src/main/java/com/heartpet/action/NoticeDAO.java
- src/main/java/com/heartpet/action/SupportDAO.java
- src/main/java/com/heartpet/action/SupportDAOImpl.java
- src/main/java/com/heartpet/admin/AdminNoticeController.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/java/com/heartpet/project/SupportController.java
- src/main/resources/mapper/support.xml
- src/main/webapp/WEB-INF/views/admin/notice_list.jsp
- src/main/webapp/WEB-INF/views/user/support/support_insert2.jsp
- target/classes/mapper/support.xml
> support login

- src/main/java/com/heartpet/model/QnaDTO.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/resources/mapper/qna.xml
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_reply_insert.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_insert.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- src/main/webapp/sql/heartpet_board.sql
- target/classes/mapper/qna.xml
> board_group 추가

- src/main/java/com/heartpet/admin/AdminReviewController.java
- src/main/webapp/WEB-INF/views/admin/qna/qna_reply_insert.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_content.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
> review 관리자 하는 중

- src/main/java/com/heartpet/model/WishVO.java
- src/main/java/com/heartpet/project/SupportController.java
- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- src/main/webapp/WEB-INF/views/user/support/support_insert2.jsp
- src/main/webapp/resources/css/mypage.css
- target/classes/mapper/mypage.xml
> smtp update

- src/main/java/com/heartpet/action/AnimalDAO.java
- src/main/java/com/heartpet/action/AnimalDAOImpl.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/resources/mapper/animal.xml
- src/main/webapp/WEB-INF/views/admin/review/review_update.jsp
- src/main/webapp/WEB-INF/views/user/review/review_insert.jsp
- target/classes/mapper/animal.xml
> animal_info

- src/main/java/com/heartpet/action/QnaDAO.java
- src/main/java/com/heartpet/admin/AdminReviewController.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/admin/review/review_content.jsp
- target/classes/mapper/review.xml
> review_delete 추가 및 오류 수정

- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- src/main/webapp/resources/css/mypage.css
- target/classes/mapper/mypage.xml
> mypage update

- src/main/java/com/heartpet/admin/AdminReviewController.java
- src/main/java/com/heartpet/model/ReviewDTO.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/webapp/WEB-INF/views/admin/fnq/fnq_content.jsp
- src/main/webapp/WEB-INF/views/admin/fnq/fnq_list.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_content.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_update.jsp
- src/main/webapp/WEB-INF/views/include/deleteModal.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_update.jsp
- src/main/webapp/resources/js/admin_list_view.js
> 삭제 모달 수정 중

- src/main/webapp/WEB-INF/views/admin/fnq/fnq_content.jsp
- src/main/webapp/WEB-INF/views/admin/fnq/fnq_list.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/fnq_list.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
> deleteModal 빼놓음

- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/webapp/WEB-INF/views/user/review/review_insert.jsp
- src/main/webapp/resources/js/fileCount.js
> fileCount 개량

- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/webapp/WEB-INF/views/user/review/review_insert.jsp
> video 수정 중

- src/main/java/com/heartpet/action/ReviewDAO.java
- src/main/java/com/heartpet/action/ReviewDAOImpl.java
- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- target/classes/mapper/review.xml
> review update

- src/main/java/com/heartpet/project/MypageController.java
> doubleCheck 수정

- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- target/classes/mapper/review.xml
> map update

- src/main/java/com/heartpet/project/MypageController.java
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
sendCheck[status.index][count]
> sendCheck[status.index][count]

- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- src/main/webapp/resources/css/list_view.css
> 관리자 회원관리 수정

- src/main/java/com/heartpet/admin/AdminQnaController.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/java/com/heartpet/project/UserReviewController.java
> qna 이미지 업로드 완료

- src/main/java/com/heartpet/admin/AdminAnimalController.java
- src/main/java/com/heartpet/admin/AdminQnaController.java
- src/main/java/com/heartpet/project/AnimalController.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/java/com/heartpet/util/CheckMimeType.java
- src/main/java/com/heartpet/util/FileUploadImage.java
- src/main/resources/mapper/review.xml
- target/classes/mapper/review.xml
> util 패키지 생성

- pom.xml
- target/m2e-wtp/web-resources/META-INF/maven/com.heartpet/project/pom.xml
> dependency 추가

- src/main/java/com/heartpet/action/NoticeDAO.java
- src/main/java/com/heartpet/action/NoticeDAOImpl.java
- src/main/java/com/heartpet/action/SupportDAO.java
- src/main/java/com/heartpet/action/SupportDAOImpl.java
- src/main/java/com/heartpet/admin/AdminNoticeController.java
- src/main/java/com/heartpet/admin/AdminSupportController.java
- src/main/java/com/heartpet/project/NoticeController.java
- src/main/resources/mapper/notice.xml
- src/main/resources/mapper/support.xml
- src/main/webapp/WEB-INF/views/admin/notice_list.jsp
- src/main/webapp/WEB-INF/views/admin/support_list.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_list.jsp
- target/classes/mapper/notice.xml
- target/classes/mapper/support.xml
> paging update

- src/main/java/com/heartpet/action/MypageDAO.java
- src/main/java/com/heartpet/action/MypageDAOImpl.java
- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/admin/notice_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- target/classes/mapper/mypage.xml
> paging finish

- src/main/resources/mapper/mypage.xml
- src/main/resources/mapper/support.xml
- target/classes/mapper/mypage.xml
- target/classes/mapper/support.xml
> 이렇게만 하면 되나?

- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
> 댓글입력 됨 수정할 거 많음

- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/resources/js/comment.js
> comment.js 삭제 모달까지 추가

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/user.xml
> 회원관리 정렬 수정중

- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/include/user_footer.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- target/classes/mapper/user.xml
> 회원관리 정렬 + 관리자 링크 수정

- src/main/java/com/heartpet/action/QnaDAOImpl.java
- src/main/java/com/heartpet/action/ReviewDAO.java
- src/main/java/com/heartpet/action/ReviewDAOImpl.java
- src/main/java/com/heartpet/model/ReviewCommentDTO.java
- src/main/resources/mapper/qna.xml
- src/main/resources/mapper/review.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/sql/heartpet_review_comment.sql
- target/classes/mapper/qna.xml
- target/classes/mapper/review.xml
- target/classes/mybatis-config.xml
> ReviewCommentDTO 생성 및 db 생성

- src/main/java/com/heartpet/action/ReviewDAO.java
- src/main/java/com/heartpet/action/ReviewDAOImpl.java
- src/main/java/com/heartpet/project/UserQnaController.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/java/com/heartpet/util/FileUploadImage.java
- src/main/resources/mapper/qna.xml
- src/main/resources/mapper/review.xml
- src/main/webapp/resources/js/qna_comment.js
- target/classes/mapper/qna.xml
- target/classes/mapper/review.xml
> review_comment

- src/main/java/com/heartpet/admin/AdminReviewController.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/java/com/heartpet/util/FileUploadImage.java
- src/main/webapp/WEB-INF/views/admin/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_content.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_list.jsp
- src/main/webapp/resources/js/review_comment.js
> review_comment 완성

- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/resources/css/list_view.css
> 회원관리 css 수정 header 수정중

- src/main/webapp/WEB-INF/views/admin/admin_main.jsp
- src/main/webapp/resources/css/admin_main.css
> admin_main 수정중

- src/main/java/com/heartpet/project/UserController.java
- src/main/java/com/heartpet/project/UserMainController.java
- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/resources/css/admin_include.css
- src/main/webapp/resources/css/main.css
- src/main/webapp/resources/css/user_include.css
- src/main/webapp/resources/css/user_qna.css
> font + header 변경

- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_grade_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_deleteCheck.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
> mypage font

- src/main/webapp/resources/css/admin_main.css
- src/main/webapp/resources/js/signin_up.js
> admin_main 수정

- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/resources/css/admin_include.css
- src/main/webapp/resources/css/user_include.css
> font admin 적용

- src/main/webapp/WEB-INF/views/admin/notice/notice_content.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_insert.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_list.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_update.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_insert.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_list.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_update.jsp
> path update

- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/resources/css/admin_update.css
- src/main/webapp/resources/css/list_view.css
> user_update 수정

- src/main/webapp/resources/js/signin_up.js
> 로그인/회원가입 수정중

- src/main/webapp/WEB-INF/views/admin/notice/notice_content.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_content.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_list.jsp
- src/main/webapp/WEB-INF/views/user/support/support_insert2.jsp
- src/main/webapp/resources/css/notice.css
- src/main/webapp/resources/css/support.css
- src/main/webapp/resources/js/signin_up.js
> notice update

- src/main/webapp/WEB-INF/views/include/admin_header.jsp
> 관리자 header 비율 수정

- src/main/webapp/WEB-INF/views/include/admin_header.jsp
- src/main/webapp/resources/css/list_view.css
> user_content 수정

- src/main/webapp/WEB-INF/views/admin/review/review_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
- src/main/webapp/resources/js/qna_comment.js
- src/main/webapp/resources/js/review_comment.js
> 댓글쓰기 테이블 생성 ajax 처리

- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/WEB-INF/views/include/pagination_update.jsp
> 오류 테스트 중 + css 수정

- src/main/java/com/heartpet/admin/AdminReviewController.java
- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/WEB-INF/views/include/pagination_update.jsp
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/user/qna/fnq_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_list.jsp
- src/main/webapp/resources/css/user_qna.css
- src/main/webapp/resources/css/user_review.css
- src/main/webapp/resources/js/admin_search.js
> css 수정 및 오류 수정 중

- src/main/java/com/heartpet/project/UserReviewController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/user/review/review_list.jsp
- src/main/webapp/resources/css/list_view.css
- src/main/webapp/resources/css/user_qna.css
- src/main/webapp/resources/css/user_review.css
- src/main/webapp/resources/js/qna_comment.js
- target/classes/mapper/review.xml
> 여러 버그들 수정 및 css

- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/resources/css/admin_animal.css
- src/main/webapp/resources/css/admin_include.css
- src/main/webapp/resources/css/admin_main.css
- src/main/webapp/resources/css/admin_update.css
- src/main/webapp/resources/css/list_view.css
- src/main/webapp/resources/css/main.css
- src/main/webapp/resources/css/mypage.css
- src/main/webapp/resources/css/notice.css
- src/main/webapp/resources/css/sign_in_up.css
- src/main/webapp/resources/css/support.css
- src/main/webapp/resources/css/user_animal_main.css
- src/main/webapp/resources/css/user_include.css
- src/main/webapp/resources/css/user_qna.css
- src/main/webapp/resources/css/user_review.css
> 회원관리 정렬 / css 수정

- src/main/java/com/heartpet/action/ReviewDAO.java
- src/main/java/com/heartpet/action/ReviewDAOImpl.java
- src/main/java/com/heartpet/admin/AdminReviewController.java
- src/main/java/com/heartpet/model/PageDTO.java
- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/admin/fnq/fnq_list.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_list.jsp
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/review.xml
> Admin_review 검색 항목 변경

- src/main/webapp/WEB-INF/views/admin/notice/notice_list.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_list.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_list.jsp
- src/main/webapp/resources/css/notice.css
- src/main/webapp/resources/css/support.css
> order update

- src/main/resources/mapper/review.xml
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/user/animal/user_animal_content.jsp
- src/main/webapp/WEB-INF/views/user/review/review_list.jsp
- src/main/webapp/resources/css/user_include.css
- src/main/webapp/resources/css/user_qna.css
- src/main/webapp/resources/css/user_review.css
- target/classes/mapper/review.xml
> user-reivew css + review

- src/main/java/com/heartpet/action/NoticeDAO.java
- src/main/java/com/heartpet/action/NoticeDAOImpl.java
- src/main/java/com/heartpet/admin/AdminNoticeController.java
- src/main/java/com/heartpet/project/NoticeController.java
- src/main/resources/mapper/notice.xml
- src/main/webapp/WEB-INF/views/admin/notice/notice_list.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_list.jsp
- target/classes/mapper/notice.xml
> search update

- src/main/java/com/heartpet/action/QnaDAO.java
- src/main/java/com/heartpet/action/QnaDAOImpl.java
- src/main/java/com/heartpet/admin/AdminQnaController.java
- src/main/resources/mapper/qna.xml
- src/main/webapp/WEB-INF/views/admin/qna/qna_list.jsp
- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/qna.xml
> admin-qna 수정중

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/project/AdminController.java
- src/main/resources/mapper/qna.xml
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- target/classes/mapper/user.xml
> user update

- src/main/webapp/resources/css/list_view.css
- target/classes/mapper/qna.xml
> 회원정보 css 수정

- src/main/webapp/resources/css/list_view.css
> label 기본 마진 없앰

- src/main/webapp/resources/css/mypage.css
> mypage css

- src/main/webapp/WEB-INF/views/user/animal/user_animal_insert.jsp
- src/main/webapp/WEB-INF/views/user/animal/user_animal_list.jsp
- src/main/webapp/resources/css/animal.css
- src/main/webapp/resources/css/user_animal_main.css
> css update

- src/main/java/com/heartpet/action/SupportDAO.java
- src/main/java/com/heartpet/action/SupportDAOImpl.java
- src/main/java/com/heartpet/project/SupportController.java
- src/main/resources/mapper/support.xml
- src/main/webapp/WEB-INF/views/user/support/support_finish.jsp
- src/main/webapp/WEB-INF/views/user/support/support_insert_js.jsp
- target/classes/mapper/support.xml
> support finish

- src/main/java/com/heartpet/admin/AdminAnimalController.java
- src/main/java/com/heartpet/project/SupportController.java
- src/main/webapp/WEB-INF/views/admin/adoptreg/adoptreg_update.jsp
> email update

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/admin/AdminController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- target/classes/mapper/user.xml
> 회원관리 검색 수정

- src/main/webapp/WEB-INF/views/admin/animal/animal_list.jsp
> admin 동물관리 검색 끝

- src/main/webapp/WEB-INF/views/user/animal/user_animal_list.jsp
- src/main/webapp/resources/css/user_animal_main.css
> 조건 검색 css 수정

- src/main/java/com/heartpet/project/AnimalController.java
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/user/animal/user_animal_insert.jsp
- src/main/webapp/resources/css/main.css
> 입소 신청 권한 기능 추가

- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/resources/css/main.css
> main css 고치는중

- src/main/webapp/WEB-INF/views/admin/admin_main.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_list.jsp
- src/main/webapp/resources/css/admin_main.css
- src/main/webapp/resources/css/notice.css
> admin-main 및 notice-list 수정중

- src/main/webapp/WEB-INF/views/admin/animal/animal_list.jsp
- src/main/webapp/WEB-INF/views/user/animal/user_animal_insert.jsp
- src/main/webapp/WEB-INF/views/user/animal/user_animal_list.jsp
- src/main/webapp/WEB-INF/views/user/notice/notice_list.jsp
- src/main/webapp/resources/css/user_animal_main.css
> user_animal 검색폼

- src/main/resources/mapper/qna.xml
- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/user/qna/fnq_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- src/main/webapp/resources/css/user_qna.css
- target/classes/mapper/qna.xml
> css qna 등 수정

- src/main/webapp/WEB-INF/views/admin/adoptreg/adoptreg_list.jsp
- src/main/webapp/WEB-INF/views/admin/animal/animal_list.jsp
> 소소한 css 수정

- src/main/java/com/heartpet/action/UserDAO.java
- src/main/java/com/heartpet/action/UserDAOImpl.java
- src/main/java/com/heartpet/admin/AdminController.java
- src/main/resources/mapper/user.xml
- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- target/classes/mapper/user.xml
> user_content delete 수정 완료

- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
> 회원 상세보기 수정

- src/main/java/com/heartpet/action/AnimalDAO.java
- src/main/java/com/heartpet/action/AnimalDAOImpl.java
- src/main/java/com/heartpet/action/ReviewDAO.java
- src/main/java/com/heartpet/action/ReviewDAOImpl.java
- src/main/java/com/heartpet/project/UserMainController.java
- src/main/resources/mapper/animal.xml
- src/main/resources/mapper/review.xml
- target/classes/mapper/animal.xml
- target/classes/mapper/review.xml
> main 출력 data 랜덤값으로 수정

- src/main/webapp/WEB-INF/views/user/qna/qna_content.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
- src/main/webapp/WEB-INF/views/user/review/review_content.jsp
- src/main/webapp/resources/css/user_qna.css
> 댓글쓰기 css 수정

- src/main/java/com/heartpet/admin/AdminQnaController.java
- src/main/webapp/WEB-INF/views/admin/qna/qna_update.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_insert.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_update.jsp
> 관리자 문의글 수정 추가

- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_grade_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_menu.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_deleteCheck.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- src/main/webapp/resources/css/mypage.css
> mypage_menu 전체 변경

- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_grade_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_menu.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_delete.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_deleteCheck.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- src/main/webapp/resources/css/mypage.css
> body div 생성

- src/main/webapp/WEB-INF/views/user/animal/user_animal_view.jsp
- src/main/webapp/resources/css/animal.css
> 동물 상세 수정 ..

- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/resources/css/mypage.css
- src/main/webapp/resources/js/signin_up.js
> mypage 회원정보변경 수정

- src/main/webapp/WEB-INF/views/user/animal/user_animal_view.jsp
- src/main/webapp/resources/css/animal.css
> animal_content css 수정중

- src/main/java/com/heartpet/action/MypageDAO.java
- src/main/java/com/heartpet/action/MypageDAOImpl.java
- src/main/java/com/heartpet/action/WishDAO.java
- src/main/java/com/heartpet/action/WishDAOImpl.java
- src/main/java/com/heartpet/project/MypageController.java
- src/main/resources/mapper/mypage.xml
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- target/classes/mapper/mypage.xml
> mypage paging

- src/main/java/com/heartpet/project/AnimalController.java
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_reg_list.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_user_update.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_wish_list.jsp
- src/main/webapp/resources/css/mypage.css
> 마이페이지 css 완성

- src/main/webapp/WEB-INF/views/user/mypage/mypage_grade_list.jsp
- src/main/webapp/resources/css/mypage.css
- src/main/webapp/resources/js/main.js
> mypage_grade_list 완성

- src/main/webapp/WEB-INF/views/user/qna/fnq_list.jsp
- src/main/webapp/resources/js/admin_search.js
> 값 못 끌고오는 버그 수정

- src/main/java/com/heartpet/project/AnimalController.java
- src/main/webapp/WEB-INF/views/user/animal/user_animal_list.jsp
- src/main/webapp/WEB-INF/views/user/qna/qna_list.jsp
> animal gogo

- src/main/webapp/WEB-INF/views/user/support/support_insert2.jsp
- src/main/webapp/resources/css/support.css
> support css

- src/main/webapp/WEB-INF/views/user/support/support_insert.jsp
- src/main/webapp/WEB-INF/views/user/support/support_insert2.jsp
- src/main/webapp/resources/css/support.css
> 후원하기 insert 완료

- src/main/webapp/WEB-INF/views/include/user_header.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_support_list.jsp
- src/main/webapp/resources/css/mypage.css
> 마이페이지 후원내역 css 완성

- src/main/webapp/WEB-INF/views/admin/animal/animal_content.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_update.jsp
- src/main/webapp/resources/css/admin_animal.css
- src/main/webapp/resources/css/list_view.css
> admin css 수정

- src/main/webapp/WEB-INF/views/admin/support/support_insert.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_update.jsp
- src/main/webapp/resources/css/support.css
> support css 수정

- src/main/java/com/heartpet/project/UserController.java
- src/main/webapp/resources/js/signin_up.js
> grade 추가, 가입 수정

- src/main/webapp/resources/css/user_review.css
- src/main/webapp/resources/js/qna_comment.js
- src/main/webapp/resources/js/review_comment.js
> 소소한 오류 수정중

- src/main/webapp/WEB-INF/views/admin/adoptreg/adoptreg_update.jsp
> adoptreg_update jsp 수정본 완성

- src/main/webapp/WEB-INF/views/admin/adoptreg/adoptreg_update.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_content.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_insert.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_update.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_insert.jsp
- src/main/webapp/WEB-INF/views/admin/support/support_update.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_insert.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- src/main/webapp/WEB-INF/views/user/mypage/mypage_adopt_complet_list.jsp
> mypage update, header

- src/main/webapp/WEB-INF/views/admin/animal/animal_content.jsp
- src/main/webapp/WEB-INF/views/admin/animal/animal_list.jsp
- src/main/webapp/WEB-INF/views/admin/review/review_content.jsp
- src/main/webapp/resources/css/admin_animal.css
- src/main/webapp/resources/css/list_view.css
> 동물관리 상세페이지

- src/main/webapp/WEB-INF/views/admin/animal/animal_insert.jsp
- src/main/webapp/resources/css/list_view.css
> animal_insert

- src/main/webapp/WEB-INF/views/admin/adoptreg/adoptreg_list.jsp
> adopreg_list 변경

- src/main/webapp/WEB-INF/views/admin/user/user_view.jsp
- src/main/webapp/WEB-INF/views/include/join.jsp
> style update

- src/main/webapp/WEB-INF/views/include/join.jsp
- src/main/webapp/resources/css/sign_in_up.css
> join css 수정

- src/main/webapp/WEB-INF/views/include/join.jsp
> placeholder 수정

- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
- src/main/webapp/WEB-INF/views/admin/user/user_update.jsp
- src/main/webapp/resources/css/admin_update.css
> 회원관리 css 수정

- src/main/webapp/WEB-INF/views/admin/notice/notice_insert.jsp
- src/main/webapp/WEB-INF/views/admin/notice/notice_update.jsp
> 공지사항 css 수정

- src/main/java/com/heartpet/admin/AdminAnimalController.java
- src/main/java/com/heartpet/project/MypageController.java
- src/main/java/com/heartpet/project/SupportController.java
> email delete

- src/main/webapp/WEB-INF/views/admin/user/user_list.jsp
> 회원관리 삭제 수정

- src/main/webapp/WEB-INF/views/include/deleteCommentModal.jsp
- src/main/webapp/resources/js/qna_comment.js
> function이름 수정
